### ISSUE TITLE
the page seems too wide.

### ISSUE THREAD

**Issue by xnng** [dreambo8563/vue-particle-effect-buttons#21]
![image](https://user-images.githubusercontent.com/38936252/58323338-41ef4d80-7e56-11e9-9a7b-cffae3ab6c9f.png)

## Expect
No horizontal scroll bar

**Comment by dreambo8563** [comment]
I will look into that

**Comment by dreambo8563** [comment]
@xnng I could not reproduce the issue on chrome and my safari.

**Comment by xnng** [comment]
I can reproduce it by all my browsers on win 10 v1903

It's very strange.

![image](https://user-images.githubusercontent.com/38936252/58379700-c6b6a480-7fd9-11e9-886a-20f1b852e794.png)

**Comment by dreambo8563** [comment]
@xnng a pr will be welcome, make a try:smiley:

**Comment by xnng** [comment]
I find a way to solve this problem on my device，although i think `calc(50vmax - 11px) === auto` in this case, I don't understand why does it behave differently on different devices. In a word, `auto` is useful，I will continue to explore it.

![2019-05-26_22-32-01](https://user-images.githubusercontent.com/38936252/58383354-3774b580-8008-11e9-80c2-9f8c68b74220.gif)
see pr #22

**Comment by dreambo8563** [comment]
demo updated
